name: Project CI
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  integration-test-frontend:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Add HTTP server
        run: npm install -g serve
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Build Frontend
        run: npm run build
      - name: Start Frontend
        run: serve -s dist
      - name: Run Playwright tests
        env:
          VUE_APP_BASE_URL: ${{ secrets.VUE_APP_BASE_URL }}
        run: VUE_APP_BASE_URL=$VUE_APP_BASE_URL npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
